### ISSUE TITLE
minify issue

### ISSUE THREAD

**Issue by qiiyue** [APISENSE/rhino-android#1]
when set minifyEnabled=true,it cannot work,can anyone help me to resolve it?

**Comment by aveuiller** [comment]
Hello,

Proguard will remove every classes which are not directly called, thus when you minify you may want to explicitly keep  classes related to `Rhino` execution.

In our Application embedding this library, we are using this [proguard configuration](https://github.com/APISENSE/bee-android/blob/develop/bee/proguard-rules.pro#L53):
```
## Rhino
-keep class javax.script.** { *; }
-keep class com.sun.script.javascript.** { *; }
-keep class org.mozilla.javascript.** { *; }
-dontwarn org.mozilla.javascript.**
-dontwarn sun.**
```

Let me know if that solves your problem.

**Comment by aveuiller** [comment]
I hope you solved your problem, I will close the issue but don't hesitate to open it again if you still have an issue with the proguard configuration.
