### ISSUE TITLE
ScriptEngineManager(null).getEngineByName("JavaScript") always null

### ISSUE THREAD

**Issue by shylendramadda** [APISENSE/rhino-android#11]
I am using JDK 13.0.2 in android studio. I am trying to create jsEngine like below:

`val jsEngine = ScriptEngineManager().getEngineByName("JavaScript")`

It is always giving me null.

Tried with:

`val jsEngine = ScriptEngineManager(null).getEngineByExtension("js")`

Also tried by passing null:

`val jsEngine = ScriptEngineManager(null).getEngineByName("JavaScript")`

Also tried changing JDK to 8 but no clue.

Please let me know what I am doing wrong here.

**Comment by aveuiller** [comment]
Hello,

Thanks for using the project! The script engine should be loaded if you use one of [those names](https://github.com/APISENSE/rhino-android/blob/develop/sun-dependencies/src/main/java/com/sun/script/javascript/RhinoScriptEngineFactory.java#L147-L153) or [the extension "js"](https://github.com/APISENSE/rhino-android/blob/develop/sun-dependencies/src/main/java/com/sun/script/javascript/RhinoScriptEngineFactory.java#L163-L165).

So the following calls should return a useable script engine: 
```kotlin
val jsEngine = ScriptEngineManager().getEngineByName("js")
val jsEngine = ScriptEngineManager().getEngineByExtension("js")
```

If you still have a null value, you should look on the Proguard side if you are using any minification.

I created a [RhinoSampleApp](https://github.com/aveuiller/RhinoSampleApp) project, which you can build with your environment and see if the script engine is rightfully returned:

<img width="377" alt="Capture d’écran 2021-06-21 à 13 44 57" src="https://user-images.githubusercontent.com/4600261/122756651-fb6bb780-d296-11eb-8326-57fd9a5981fc.png">

Let me know if you still have an issue. If so, it would be great to have more details about:
- The version of your Android SDK
- Your Proguard configuration, if any

**Comment by shylendramadda** [comment]
Thank you for your reply.

It's worked with "rhino"

val jsEngine = ScriptEngineManager().getEngineByName("rhino")



Regards,
Shailendra.

**Comment by aveuiller** [comment]
Great, I'll close then.

Don't hesitate if you have another question :)

**Comment by shylendramadda** [comment]
sure, definitely.


Regards,
Shailendra.
