### ISSUE TITLE
 I have problems using Math.asinh . HELP ME !

### ISSUE THREAD

**Issue by ThucVan** [APISENSE/rhino-android#12]
org.mozilla.javascript.EcmaError: TypeError: Cannot find function asinh in object [object Math]

**Comment by aveuiller** [comment]
Hello,

Given this issue on Rhino https://github.com/mozilla/rhino/issues/200 and their [release description](https://github.com/mozilla/rhino/releases/tag/Rhino1_7_11_Release), it seems like the function `asinh` has been implemented into 1.7.11.

This project currently embeds 1.7.10, so your error makes sense. I'll update the dependency when I get the time.

**Comment by aveuiller** [comment]
I just released `v1.2.0` which should solve your issue.
