### ISSUE TITLE
can you fix #1149 ?

### ISSUE THREAD

**Issue by normidar** [APISENSE/rhino-android#14]
see https://github.com/mozilla/rhino/issues/1149

**Comment by CPTProgrammer** [comment]
`v1.2.0` uses the problematic `Rhino 1.7.14`.
You can try downgrading the `rhino-android` version to `v1.1.1`: 
```diff
dependencies {
    ...
-   implementation "io.apisense:rhino-android:1.2.0"
+   implementation "io.apisense:rhino-android:1.1.1"
    ...
}
```

It works for me :)
