### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by rpavliuk** [APISENSE/rhino-android#2]
Can you throw exception or return 0, if it possible, when division by zero occurs?
Because I get infinity sign: ∞ and it's not very convenient.
Thanks

**Comment by aveuiller** [comment]
Hello, unfortunately this library only aim to provide you access to Rhino, not modify its behavior.

This project embed the Rhino implementation by Mozilla (https://github.com/mozilla/rhino), I think it's what you are looking for.

**Comment by Skullper** [comment]
Ok, thx
