### ISSUE TITLE
Use of power in calculations

### ISSUE THREAD

**Issue by rpavliuk** [APISENSE/rhino-android#3]
How can I use in calculations power(^)?

Example: 2^2=4. When I call engine.eval() I got 0

How can I fix this?

**Comment by jbeard4** [comment]
In JavaScript, ^ is the operator for bitwise XOR: https://www.tutorialspoint.com/javascript/javascript_operators.htm

Instead, use Math.pow(2, 2)

**Comment by rpavliuk** [comment]
@jbeard4 it's not very fits my case. Maybe you know other approach or lib to calculate large and complex formulas?

Thanks

**Comment by jbeard4** [comment]
Unfortunately, js does not give you a lot of control over syntax. Other languages let you do "operator overloading" and redefine the meaning of operators for classes of objects - but JavaScript does not. So, I think you are pretty much stuck with js syntax.

**Comment by rpavliuk** [comment]
Ok, thanks for answers

**Comment by aveuiller** [comment]
Thanks @jbeard4 for the detailed explanation :)
