### ISSUE TITLE
proguard-rules problem

### ISSUE THREAD

**Issue by FlogFly** [APISENSE/rhino-android#4]
If I want to write proguard rules content in the ``proguard-rules.pro`` for rhino-android,  How should I write？？？？  Thanks

**Comment by aveuiller** [comment]
Hello,

I think you can find your answer on this issue: https://github.com/APISENSE/rhino-android/issues/1

**Comment by aveuiller** [comment]
I hope you solved your problem, I will close the issue but don't hesitate to open it again if you still have an issue with the proguard configuration.

You can find a working example of the proguard configuration in this project: https://github.com/aveuiller/RhinoSampleApp
